all:
	gcc -lstdc++ -o gen gen.cpp
	./gen
	gcc -lstdc++ -o main main.cpp
	./main
	cat BF.txt
	cat BB.txt
	cat DP.txt
	./gen
	./main
	cat BF.txt
	cat BB.txt
	cat DP.txt
	./gen
	./main
	cat BF.txt
	cat BB.txt
	cat DP.txt
